version : '3.1'

services : 
  redis-master :
    image : redis:latest
    container_name : webserver
    restart : unless-stopped
    ports :
      - "6379"

  redis-slave :
    image : gcr.io/google_samples/gb-redisslave:v1
    ports :
      - "30000-30020:6379"
    environment : 
      - GET_HOSTS_FROM=dns

  frontend : 
    image : gcr.io/google_samples/gb-frontend:v3
    ports :
      - "8080:80"
    environment : 
      - GET_HOSTS_FROM=dns

